version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '30333:30333'
      - '9933:9933'
    volumes:
      - ./data/customSpecRaw.json:/app/customSpecRaw.json:ro
      - ./data/node1/node_key:/app/node_key:ro
      - ./data/node1/node:/app/node
    command: >
      qmc-node
      --name node1
      --chain=customSpecRaw.json
      --rpc-cors all
      --validator
      --rpc-methods=Unsafe
      --unsafe-rpc-external
      --password="validator_1"
      --no-mdns
      --base-path ./node
      --port 30333
      --rpc-port 9933
      --node-key-file ./node_key
      --offchain-worker Always
      --sae-id Test_1SAE
      --addr-pqkd http://172.16.0.101:3000
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '30334:30333'
      - '9934:9933'
    volumes:
      - ./data/customSpecRaw.json:/app/customSpecRaw.json:ro
      - ./data/node2/node_key:/app/node_key:ro
      - ./data/node2/node:/app/node
    command: >
      qmc-node
      --name node2
      --chain=customSpecRaw.json
      --rpc-cors all
      --validator
      --rpc-methods=Unsafe
      --unsafe-rpc-external
      --password="validator_2"
      --no-mdns
      --base-path ./node
      --port 30333
      --rpc-port 9933
      --node-key-file ./node_key
      --offchain-worker Always
      --sae-id Test_2SAE
      --addr-pqkd http://172.16.0.102:3000
  node3:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '30335:30333'
      - '9935:9933'
    volumes:
      - ./data/customSpecRaw.json:/app/customSpecRaw.json:ro
      - ./data/node3/node_key:/app/node_key:ro
      - ./data/node3/node:/app/node
    command: >
      qmc-node
      --name node3
      --chain=customSpecRaw.json
      --rpc-cors all
      --validator
      --rpc-methods=Unsafe
      --unsafe-rpc-external
      --password="validator_3"
      --no-mdns
      --base-path ./node
      --port 30333
      --rpc-port 9933
      --node-key-file ./node_key
      --offchain-worker Always
      --sae-id BobSAE
      --addr-pqkd http://172.16.0.103:3000
  node4:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '30336:30333'
      - '9936:9933'
    volumes:
      - ./data/customSpecRaw.json:/app/customSpecRaw.json:ro
      - ./data/node4/node_key:/app/node_key:ro
      - ./data/node4/node:/app/node
    command: >
      qmc-node
      --name node4
      --chain=customSpecRaw.json
      --rpc-cors all
      --validator
      --rpc-methods=Unsafe
      --unsafe-rpc-external
      --password="validator_4"
      --no-mdns
      --base-path ./node
      --port 30333
      --rpc-port 9933
      --node-key-file ./node_key
      --offchain-worker Always
      --sae-id Validator_2SAE
      --addr-pqkd http://172.16.0.104:3000

networks:
  default:
    driver: bridge