[package]
name = "quantum-metachain"
version = "0.1.0"
edition = "2021"

[dependencies]
qmc-p2p = { version = "0.1.0", path = "../communication/p2p" }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
