[package]
name = "qmc-node"
version = "0.0.1"
description = "Quantum metachain"
authors = ["Quantum Blockchains"]
homepage = "https://quantumblockchains.io/"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/Quantum-Blockchains/quantum-metachain"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "qmc-node"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }

sc-cli = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", features = ["wasmtime"] , branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-core = { version = "6.0.0", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", features = ["wasmtime"] , branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-service = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", features = ["wasmtime"] , branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-network = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-keystore = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-transaction-pool-api = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-consensus-aura = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-consensus-aura = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-finality-grandpa = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-finality-grandpa = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-runtime = { version = "6.0.0", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-timestamp = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-keyring = { version = "6.0.0", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
pallet-transaction-payment = { version = "4.0.0-dev", default-features = false, git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.15.1", features = ["server"] }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-rpc-api = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
sc-basic-authorship = { version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
substrate-frame-rpc-system = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
pallet-transaction-payment-rpc = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
futures = '0.3.1'
sc-consensus-manual-seal = {version = "0.10.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts"}
# libp2p = "0.48.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.86"
reqwest = "0.11.12"
base64 = "0.13.0"
hex = "0.4.3"

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }
frame-benchmarking-cli = { version = "4.0.0-dev", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }

# Local Dependencies
qmc-runtime = { version = "0.0.1", path = "../runtime" }

# CLI-specific dependencies
try-runtime-cli = { version = "0.10.0-dev", optional = true, git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/Quantum-Blockchains/substrate.git", branch = "kostia/JEQB-127/Get_pre-shared_key_before_p2p_starts" }

[features]
default = []
runtime-benchmarks = ["qmc-runtime/runtime-benchmarks"]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["qmc-runtime/try-runtime", "try-runtime-cli"]
