#
# Client proxy
#

config.type=client

server.proxy.host=31.182.67.107
server.proxy.port=9998

client.proxy.id=Bob
client.proxy.host=192.168.8.106

client.proxy.listening=8080:Alice

client.proxy.endpoint=8080;192.168.8.103:80,

server.service.host=31.182.67.107
server.service.port=9991

