#
# Client proxy
#

config.type=client

server.proxy.host=31.182.67.107
server.proxy.port=9996

client.proxy.id=Alice
client.proxy.host=192.168.1.200

client.proxy.listening=8080:config:Bob
client.proxy.listening=8082:kme:Bob
client.proxy.listening=8083:notification:Bob
client.proxy.listening=8084:qkd:Bob

			
client.proxy.endpoint=config;192.168.1.80:80
client.proxy.endpoint=kme;192.168.1.80:8082
client.proxy.endpoint=notification;192.168.1.80:8083
client.proxy.endpoint=qkd;192.168.1.80:8084

server.service.host=192.168.1.200
server.service.port=9991

