name: Rust CI - checks

on:
  push:
    branches:
      - '**'

jobs:
  goci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Rust files
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo fmt -- --check
