name: runner-test

on:
  pull_request:
    branches:
      - '**'
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main

jobs:
  check-runner-and-lint:
    name: Run pytest and linter
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 --ignore="E501, F401" .

      - name: Unit tests
        run: |
          pytest runner

      - name: Integration tests
        run: |
          python3 runner/app.py test