name: Rust CI

on:
  push:
    branches:
      - '**'

jobs:
  goci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test Rust files
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo fmt -- --check

      - name: Build Rust projects
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build
